### ISSUE TITLE
"No books added" message do not appear to the user if they start a new

### ISSUE THREAD

**Issue by AmineHLub** [benshidanny11/awesomebooks#2]
### Issue :
**_You've done very well so far However there might be some tricks to be added to make the UX feel better._**

The "No books added" appears only when the user adds and removes an element.
to fix that add :
(!localStorage.getItem('booksData')) to the condition of creation of that message

if (convertedBooks && convertedBooks.length === 0 **&& !localStorage.getItem('booksData')** ) {
    document.getElementById('bookstatus').innerHTML = 'No books added';

_Optional :_
_- Avoid using <br> => use border bottom for example instead;_
_- style the h2 tags to follow the design (they are bold)_

**Comment by Whoistolu** [comment]
## Hello [@AmineHLub](https://github.com/AmineHLub),
## We appreciate your feedback.
- The issues have been fixed.
