### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by ntzwilly** [benshidanny11/awesomebooks#6]
Hi @Whoistolu,

You did a nice job on your project, you can still improve it by applying this: 

- Remove the white space when you add a new book
- Make  the book-list-container to have a scroll when you add more books
- You are using a single javascript file. You can create a new file for the navigation functionalities for the good readability of your code.

**Comment by Whoistolu** [comment]
## Hello [@ntzwilly](https://github.com/ntzwilly),
## Thank you for your feedback.
- I can assure you these issues will be fixed within an hour.
